ALTER TABLE endpoints 
ADD COLUMN IF NOT EXISTS cpu_model TEXT,
ADD COLUMN IF NOT EXISTS total_ram_bytes BIGINT,
ADD COLUMN IF NOT EXISTS total_disk_bytes BIGINT,
ADD COLUMN IF NOT EXISTS free_disk_bytes BIGINT,
ADD COLUMN IF NOT EXISTS bios_version TEXT,
ADD COLUMN IF NOT EXISTS manufacturer TEXT,
ADD COLUMN IF NOT EXISTS model TEXT;
